# Generated by Django 3.1.1 on 2021-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle_1h',
            name='id',
        ),
        migrations.RemoveField(
            model_name='candle_1m',
            name='id',
        ),
        migrations.RemoveField(
            model_name='candle_1s',
            name='id',
        ),
        migrations.AlterField(
            model_name='candle_1h',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candle_1m',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candle_1s',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signalevents',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
