# Generated by Django 3.1.1 on 2021-01-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20210111_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bb', max_length=10)),
                ('bbandN', models.IntegerField(default=20)),
                ('bbandk', models.FloatField(default=2.0)),
            ],
        ),
        migrations.CreateModel(
            name='EmaParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ema', max_length=10)),
                ('emaperiod1', models.IntegerField(default=7)),
                ('emaperiod2', models.IntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='IchimokuParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ichimoku', max_length=10)),
                ('ichimokut', models.IntegerField(default=12)),
                ('ichimokuk', models.IntegerField(default=26)),
                ('ichimokus', models.IntegerField(default=52)),
            ],
        ),
        migrations.CreateModel(
            name='MacdParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Macd', max_length=10)),
                ('macdfastperiod', models.IntegerField(default=12)),
                ('macdslowperiod', models.IntegerField(default=26)),
                ('macdsignaleriod', models.IntegerField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='RsiParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rsi', max_length=10)),
                ('rsiperiod', models.IntegerField(default=14)),
                ('rsibuythread', models.FloatField(default=30.0)),
                ('rsisellthread', models.FloatField(default=70.0)),
            ],
        ),
        migrations.CreateModel(
            name='SmaParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sma', max_length=10)),
                ('smaperiod1', models.IntegerField(default=26)),
                ('smaperiod2', models.IntegerField(default=52)),
            ],
        ),
    ]
