# Generated by Django 3.1.1 on 2021-01-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_bbparams_emaparams_ichimokuparams_macdparams_rsiparams_smaparams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macdparams',
            old_name='macdsignaleriod',
            new_name='macdsignalperiod',
        ),
    ]
